### ISSUE TITLE
Links in tags index to tagged pages are incorrect on Windows

### ISSUE THREAD

**Issue by schrursk** [squidfunk/mkdocs-material#3865]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Adding support for tags in a subfolder in my documentation project did cause warnings at mkdocs serve.
Additionally the tag links, from the tags.md inside subfolder, are not working and showing the 404 not found page.

### Expected behaviour

Using tags.md in a subfolder should not cause warning as mkdocs serve building time & tag links should work.

### Actual behaviour

Using tags.md in a subfolder cause warning & tag links do not work (404 not found)

```
(venv) PS C:\test\mkdocs test> mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in   
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in   
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in   
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in   
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in   
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in   
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in   
            the documentation files.
INFO     -  Documentation built in 0.22 seconds
INFO     -  [11:46:54] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO     -  [11:46:54] Serving on http://127.0.0.1:8000/
INFO     -  [11:47:07] Browser connected: http://127.0.0.1:8000/
INFO     -  [11:47:12] Browser connected: http://127.0.0.1:8000/getting-started/getting-started/
INFO     -  [11:47:14] Browser connected: http://127.0.0.1:8000/getting-started/tags/
WARNING  -  [11:47:16] "GET /getting-started/tags/getting-started/getting-started.md HTTP/1.1" code 404
```

### Steps to reproduce

1. Create a simple mkdocs.yml with tags and tags_file support (see below with the yml file I am using)
2. Create the tags.md page in a 'getting-started' subfolder and reference in the mkdocs.yml
3. Run mkdocs serve

### Package versions

- Python: `python 3.9.7`
- MkDocs: `mkdocs 1.3.0`
- Material: `version 8.2.12`

### Configuration

```yaml
site_name: 'Test Tags'
site_description: 'Description'
site_author: 'Company'

nav:
  - Home:
    - Introduction: index.md
    - Getting Started:
        - getting-started/getting-started.md
        - Tags: getting-started/tags.md

theme:
  name: 'material'

markdown_extensions:
  - meta

plugins:
  - search:
      prebuild_index: false
  - tags:
      tags_file: getting-started/tags.md
```

### System information

- Operating system: windows
- Browser: Chrome

**Comment by squidfunk** [comment]
Thanks for reporting. I'm not able to reproduce this. I've tested with the following configuration:

``` yaml
plugins:
  - tags:
      tags_file: reference/foo/tags.md
nav:
  - Reference:
    - Tags: reference/foo/tags.md
```

All links work, no 404s. Please provide a self-contained example that reproduces the issue and append it here as a zip file.

**Comment by schrursk** [comment]
Thanks you for the swift reaction

Please find the files in the zip file & some test pictures.
[mkdocs test.zip](https://github.com/squidfunk/mkdocs-material/files/8598804/mkdocs.test.zip)

<img width="1920" alt="pic1_tags" src="https://user-images.githubusercontent.com/15106171/166144066-d1143f5e-4976-437e-9c35-3f8c6b281716.png">

![pic2_404](https://user-images.githubusercontent.com/15106171/166144076-8cdaeba9-f16f-449b-8cad-0e70aef552e6.png)

FYI: Using the tags.md directly inside the docs folder does not give any issue.

**Comment by squidfunk** [comment]
Works on my machine. Then it's very likely related to Windows paths. PR appreciated.

**Comment by squidfunk** [comment]
Okay, I think I have an idea what _might_ be the problem, but I can't test it as I don't have a Windows machine. This issue may have been fixed in fd60d5bda. You can install from git and check whether the issue persists:

```
pip install git+https://github.com/squidfunk/mkdocs-material.git
```

**Comment by schrursk** [comment]
Thanks for the additional investigation.

I executed the pip install and retested:

>(venv) PS C:\test\mkdocs test> pip install git+https://github.com/squidfunk/mkdocs-material.git
Collecting git+https://github.com/squidfunk/mkdocs-material.git
  Cloning https://github.com/squidfunk/mkdocs-material.git to c:\users\eu0847\appdata\local\temp\pip-req-build-6pw1hq7d
  Running command git clone --filter=blob:none -q https://github.com/squidfunk/mkdocs-material.git 'C:\Users\EU0847\AppData\Local\Temp\pip-req-build-6pw1hq7d'
  Resolved https://github.com/squidfunk/mkdocs-material.git to commit fd60d5bdae7ea957a0b359168b72183db357802b
  Preparing metadata (setup.py) ... done
Requirement already satisfied: jinja2>=2.11.1 in c:\test\venv\lib\site-packages (from mkdocs-material==8.2.12) (3.1.2)
Requirement already satisfied: markdown>=3.2 in c:\test\venv\lib\site-packages (from mkdocs-material==8.2.12) (3.3.6)
Collecting mkdocs>=1.3.0
  Using cached mkdocs-1.3.0-py3-none-any.whl (3.7 MB)
Successfully built mkdocs-material
Installing collected packages: mkdocs, mkdocs-material
Successfully installed mkdocs-1.3.0 mkdocs-material-8.2.12
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the 'C:\test\venv\Scripts\python.exe -m pip install --upgrade pip' command.
(venv) PS C:\test\mkdocs test> mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in the documentation files.
INFO     -  Documentation built in 0.23 seconds
INFO     -  [14:36:07] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO     -  [14:36:07] Serving on http://127.0.0.1:8000/
INFO     -  [14:36:08] Browser connected: http://127.0.0.1:8000/getting-started/tags/
INFO     -  [14:36:28] Browser connected: http://127.0.0.1:8000/getting-started/getting-started/
INFO     -  [14:36:29] Browser connected: http://127.0.0.1:8000/getting-started/getting-started/
INFO     -  [14:36:31] Browser connected: http://127.0.0.1:8000/getting-started/tags/
WARNING  -  [14:36:32] "GET /getting-started/tags/getting-started/getting-started.md HTTP/1.1" code 404

Result: I still have the warnings & the 404 link issue.

**Comment by squidfunk** [comment]
Could you help debug the problem? The tag links are generated at the following location:

https://github.com/squidfunk/mkdocs-material/blob/fd60d5bdae7ea957a0b359168b72183db357802b/src/plugins/tags/plugin.py#L105-L122

Sadly, as mentioned, I don't have a Windows machine at my disposal. I can't reproduce the problem on macOS.

**Comment by schrursk** [comment]
Yes, I willing to help :-). Sadly I'm no python programmer ... However, I can add debug prints to provide some debug info .. see example:

<img width="949" alt="image" src="https://user-images.githubusercontent.com/15106171/166147536-9d1ea198-cd2f-4d76-9218-bcaed054b54c.png">

Maybe, you could add the required debug printing logs inside the example code (plugin.py), I'm happy to run it.

**Comment by schrursk** [comment]
Add debug prints:
```
    def __render_tag_links(self, tag, pages):
        content = [f"## <span class=\"md-tag\">{tag}</span>", ""]
        print("debug info tag:",tag)
        print("debug info pages:",pages)
        for page in pages:
            url = utils.get_relative_url(
                page.file.src_path,
                self.tags_file.src_path
            )
            print("url1:",url)
            # Ensure forward slashes, as we have to use the path of the source
            # file which contains the operating system's path separator.
            content.append("- [{}]({})".format(
                page.meta.get("title", page.title),
                url.replace(os.path.sep, "/")
            ))
            print("url2:",url)
        print("debug info page:",page)
        # Return rendered tag links
        return "\n".join(content)
```

Result
```
(venv) PS C:\test\mkdocs test> mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
debug info tag: CSS
debug info pages: [Page(title='Getting started', url='/getting-started/getting-started/')]
url1: getting-started\getting-started.md
url2: getting-started\getting-started.md
debug info page: Page(title='Getting started', url='/getting-started/getting-started/')
debug info tag: HTML5
debug info pages: [Page(title='Getting started', url='/getting-started/getting-started/')]
url1: getting-started\getting-started.md
url2: getting-started\getting-started.md
debug info page: Page(title='Getting started', url='/getting-started/getting-started/')
debug info tag: JavaScript
debug info pages: [Page(title='Getting started', url='/getting-started/getting-started/')]
url1: getting-started\getting-started.md
url2: getting-started\getting-started.md
debug info page: Page(title='Getting started', url='/getting-started/getting-started/')
debug info tag: Other
debug info pages: [Page(title='Getting started', url='/getting-started/getting-started/')]
url1: getting-started\getting-started.md
url2: getting-started\getting-started.md
debug info page: Page(title='Getting started', url='/getting-started/getting-started/')
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in  
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in  
debug info tag: HTML5
debug info pages: [Page(title='Getting started', url='/getting-started/getting-started/')]
url1: getting-started\getting-started.md
url2: getting-started\getting-started.md
debug info page: Page(title='Getting started', url='/getting-started/getting-started/')
debug info tag: JavaScript
debug info pages: [Page(title='Getting started', url='/getting-started/getting-started/')]
url1: getting-started\getting-started.md
url2: getting-started\getting-started.md
debug info page: Page(title='Getting started', url='/getting-started/getting-started/')
debug info tag: Other
debug info pages: [Page(title='Getting started', url='/getting-started/getting-started/')]
url1: getting-started\getting-started.md
url2: getting-started\getting-started.md
debug info page: Page(title='Getting started', url='/getting-started/getting-started/')
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in  
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in  
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in  
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in  
            the documentation files.
INFO     -  Documentation built in 0.23 seconds
INFO     -  [15:34:51] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO     -  [15:34:51] Serving on http://127.0.0.1:8000/
INFO     -  [15:34:53] Browser connected: http://127.0.0.1:8000/getting-started/tags/

```

Hopefully it helps.

**Comment by squidfunk** [comment]
Could you print the `content` variable? After adding the replace I'm really wondering why the links still have the wrong path separtor.

**Comment by schrursk** [comment]
sure. Hope it helps:

```
    def __render_tag_links(self, tag, pages):
        content = [f"## <span class=\"md-tag\">{tag}</span>", ""]
        print("debug info tag:",tag)
        print("debug info pages:",pages)
        for page in pages:
            url = utils.get_relative_url(
                page.file.src_path,
                self.tags_file.src_path
            )
            print("url1:",url)
            # Ensure forward slashes, as we have to use the path of the source
            # file which contains the operating system's path separator.
            content.append("- [{}]({})".format(
                page.meta.get("title", page.title),
                url.replace(os.path.sep, "/")
            ))
            print("url2:",url)
            print("debug info content1:",content)
        print("debug info page:",page)
        print("debug info -----content2:", content)
        # Return rendered tag links
        return "\n".join(content)
```

```
(venv) PS C:\test\mkdocs test> mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
debug info tag: CSS
debug info pages: [Page(title='Getting started', url='/getting-started/getting-started/')]
url1: getting-started\getting-started.md
url2: getting-started\getting-started.md
debug info content1: ['## <span class="md-tag">CSS</span>', '', '- [Getting started](getting-started/getting-started.md)']
debug info page: Page(title='Getting started', url='/getting-started/getting-started/')
debug info -----content2: ['## <span class="md-tag">CSS</span>', '', '- [Getting started](getting-started/getting-started.md)']
debug info tag: HTML5
debug info pages: [Page(title='Getting started', url='/getting-started/getting-started/')]
url1: getting-started\getting-started.md
url2: getting-started\getting-started.md
debug info content1: ['## <span class="md-tag">HTML5</span>', '', '- [Getting started](getting-started/getting-started.md)']
debug info page: Page(title='Getting started', url='/getting-started/getting-started/')
debug info -----content2: ['## <span class="md-tag">HTML5</span>', '', '- [Getting started](getting-started/getting-started.md)']
debug info tag: JavaScript
debug info pages: [Page(title='Getting started', url='/getting-started/getting-started/')]
url1: getting-started\getting-started.md
url2: getting-started\getting-started.md
debug info content1: ['## <span class="md-tag">JavaScript</span>', '', '- [Getting started](getting-started/getting-started.md)']
debug info page: Page(title='Getting started', url='/getting-started/getting-started/')
debug info -----content2: ['## <span class="md-tag">JavaScript</span>', '', '- [Getting started](getting-started/getting-started.md)']
debug info tag: Other
debug info pages: [Page(title='Getting started', url='/getting-started/getting-started/')]
url1: getting-started\getting-started.md
url2: getting-started\getting-started.md
debug info content1: ['## <span class="md-tag">Other</span>', '', '- [Getting started](getting-started/getting-started.md)']
debug info page: Page(title='Getting started', url='/getting-started/getting-started/')
debug info -----content2: ['## <span class="md-tag">Other</span>', '', '- [Getting started](getting-started/getting-started.md)']
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in  
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in  
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in  
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in  
            the documentation files.
debug info tag: CSS
debug info pages: [Page(title='Getting started', url='/getting-started/getting-started/')]
url1: getting-started\getting-started.md
url2: getting-started\getting-started.md
debug info content1: ['## <span class="md-tag">CSS</span>', '', '- [Getting started](getting-started/getting-started.md)']
debug info page: Page(title='Getting started', url='/getting-started/getting-started/')
debug info -----content2: ['## <span class="md-tag">CSS</span>', '', '- [Getting started](getting-started/getting-started.md)']
debug info tag: HTML5
debug info pages: [Page(title='Getting started', url='/getting-started/getting-started/')]
url1: getting-started\getting-started.md
url2: getting-started\getting-started.md
debug info content1: ['## <span class="md-tag">HTML5</span>', '', '- [Getting started](getting-started/getting-started.md)']
debug info page: Page(title='Getting started', url='/getting-started/getting-started/')
debug info -----content2: ['## <span class="md-tag">HTML5</span>', '', '- [Getting started](getting-started/getting-started.md)']
debug info tag: JavaScript
debug info pages: [Page(title='Getting started', url='/getting-started/getting-started/')]
url1: getting-started\getting-started.md
url2: getting-started\getting-started.md
debug info content1: ['## <span class="md-tag">JavaScript</span>', '', '- [Getting started](getting-started/getting-started.md)']
debug info page: Page(title='Getting started', url='/getting-started/getting-started/')
debug info -----content2: ['## <span class="md-tag">JavaScript</span>', '', '- [Getting started](getting-started/getting-started.md)']
debug info tag: Other
debug info pages: [Page(title='Getting started', url='/getting-started/getting-started/')]
url1: getting-started\getting-started.md
url2: getting-started\getting-started.md
debug info content1: ['## <span class="md-tag">Other</span>', '', '- [Getting started](getting-started/getting-started.md)']
debug info page: Page(title='Getting started', url='/getting-started/getting-started/')
debug info -----content2: ['## <span class="md-tag">Other</span>', '', '- [Getting started](getting-started/getting-started.md)']
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in  
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in  
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in  
            the documentation files.
WARNING  -  Documentation file 'getting-started\tags.md' contains a link to 'getting-started\getting-started\getting-started.md' which is not found in  
            the documentation files.
INFO     -  Documentation built in 0.22 seconds
INFO     -  [16:09:18] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO     -  [16:09:18] Serving on http://127.0.0.1:8000/
INFO     -  [16:09:18] Browser connected: http://127.0.0.1:8000/getting-started/tags/

```

**Comment by squidfunk** [comment]
Another attempt to find the error and fix it in 36d50811d. I think the `get_normalize_url` function does not handle Windows path separators, which is why I moved the replacement up. Could you try with the latest `master`?

**Comment by schrursk** [comment]
installed latest master & tested

```
Successfully uninstalled mkdocs-material-8.2.12
(venv) PS C:\test\mkdocs test> pip install git+https://github.com/squidfunk/mkdocs-material.git
Collecting git+https://github.com/squidfunk/mkdocs-material.git
  Cloning https://github.com/squidfunk/mkdocs-material.git to c:\users\eu0847\appdata\local\temp\pip-req-build-mu7r0tzv
  Running command git clone --filter=blob:none -q https://github.com/squidfunk/mkdocs-material.git 'C:\Users\EU0847\AppData\Local\Temp\pip-req-build-mu7
r0tzv'
  Resolved https://github.com/squidfunk/mkdocs-material.git to commit 36d50811dc6270afb3403e82fc8501def0f494f4
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\test\venv\lib\site-packages (from packaging>=20.5->mkdocs>=1.3.0->mkdocs-material==8.2.12)
 (3.0.8)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\test\venv\lib\site-packages (from packaging>=20.5->mkdocs>=1.3.0->mkdocs-material==8.2.12)
 (3.0.8)
Requirement already satisfied: six>=1.5 in c:\test\venv\lib\site-packages (from python-dateutil>=2.8.1->ghp-import>=1.0->mkdocs>=1.3.0->mkdocs-material=
=8.2.12) (1.16.0)
Building wheels for collected packages: mkdocs-material
  Building wheel for mkdocs-material (setup.py) ... done
  Created wheel for mkdocs-material: filename=mkdocs_material-8.2.12-py3-none-any.whl size=5100594 sha256=f159f39df9334df32cd156969cbdcdd4a394e783715c3e
8f78e916788ebbba27
  Stored in directory: C:\Users\EU0847\AppData\Local\Temp\pip-ephem-wheel-cache-5s0utvrq\wheels\65\0d\fd\898a17bfacbbbddf3b570ab8e62d8581f3ec2e33c346240
911
Successfully built mkdocs-material
Installing collected packages: mkdocs-material
Successfully installed mkdocs-material-8.2.12
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the 'C:\test\venv\Scripts\python.exe -m pip install --upgrade pip' command.
(venv) PS C:\test\mkdocs test> mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
INFO     -  Documentation built in 0.22 seconds
INFO     -  [16:46:15] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO     -  [16:46:15] Serving on http://127.0.0.1:8000/
INFO     -  [16:46:17] Browser connected: http://127.0.0.1:8000/getting-started/tags/
INFO     -  [16:46:17] Browser connected: http://127.0.0.1:8000/getting-started/tags/
INFO     -  [16:46:20] Browser connected: http://127.0.0.1:8000/
INFO     -  [16:46:23] Browser connected: http://127.0.0.1:8000/getting-started/tags/
INFO     -  [16:46:24] Browser connected: http://127.0.0.1:8000/getting-started/getting-started/
INFO     -  [16:46:53] Browser connected: http://127.0.0.1:8000/getting-started/tags/
INFO     -  [16:46:55] Browser connected: http://127.0.0.1:8000/getting-started/getting-started/
INFO     -  [16:46:56] Browser connected: http://127.0.0.1:8000/getting-started/tags/
```

Bingo! Works as intended now :-)
No "Warnings" anymore & links are working.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/15106171/166151221-a6b471a4-3181-411f-bc29-35afabad04b3.png">

**Comment by squidfunk** [comment]
Perfect, so it's indeed the path resolution bug, but I'm glad we could fix it. Thanks for your support!

**Comment by schrursk** [comment]
Thank you for your swift investigation & solution. Even on a Sunday & holiday (labor day). Dedication I would say!

Thank you again.

**Comment by squidfunk** [comment]
Released as part of 8.2.13.
