### ISSUE TITLE
Clicking on anchor links (page jumps) is not accurate

### ISSUE THREAD

**Issue by Mehran-Baghi** [squidfunk/mkdocs-material#91]
## Description

In order to add citation to my document I need to link the sentences to a footnote section (References). I tried to embed html anchor tag in my markdown like [this](http://stackoverflow.com/questions/5319754/cross-reference-named-anchor-in-markdown), However:

### Expected behavior

I expect when I click the link:
![1](https://cloud.githubusercontent.com/assets/17176259/21783494/c6b91bc4-d6cc-11e6-9eeb-4748bdb1cd6b.jpg)
It jump exactly to the anchor point, like this in the default theme:
![2](https://cloud.githubusercontent.com/assets/17176259/21783557/24e28a00-d6cd-11e6-8466-e13e8ad71257.jpg)

### Actual behavior

However in material theme it lands a few line blew:
![3](https://cloud.githubusercontent.com/assets/17176259/21783611/5fb82e28-d6cd-11e6-9704-b5cf32643fa2.jpg)

### Steps to reproduce the bug

here is my index.md file used to produce above pictures:
[index.txt](https://github.com/squidfunk/mkdocs-material/files/694704/index.txt)
Define anchor point: `<a id="cite_note-1"></a>`
Link to anchor: `[[1]](#cite_note-1)`

### Package versions

- Python: `Python 2.7.9`
- MkDocs: `mkdocs, version 0.16.1`
- Material: `Version: 0.2.4`

### System information

- OS: Debain Gnu/Linux
- Browser: Not relevant

**Comment by squidfunk** [comment]
Should be fixed in bfca02762d325324191beb8325e77360f5679cd6, please check and confirm.

**Comment by Mehran-Baghi** [comment]
Yes, now it works like a charm!  :sparkles:  :ok_hand:

**Comment by Mehran-Baghi** [comment]
Hi
I have this bug again with `Footnotes` extension.

**Comment by Mehran-Baghi** [comment]
Hi
I have this bug again with `Footnotes` extension.

**Comment by rianquinn** [comment]
I am still having this issue. If I add a custom anchor, when I click on the anchor, it scrolls just past the anchor. It appears as if it's scrolling to the correct location but not taking the height of the top header into account, so the header is covering up the anchor. 

Any thoughts?

**Comment by squidfunk** [comment]
Custom anchors are currently not supported, as this could break stuff in unpredictable ways.

**Comment by rianquinn** [comment]
That's fine. Is there a way to only show the TOC on the sidebar for headers 1 and 2. Basically, if I use the anchors that the TOC generates, they work great. The problem is, for me to get anchors for header 3, I need to tell the TOC that I want 1-3, but that causes the sidebar to have 1-3 which is a mess. What I want is for all of the headers to have anchors, but the sidebar only show 1-2.

**Comment by squidfunk** [comment]
Please us the search on this and MkDocs's issue tracker. This was discussed in detail plenty of times.

**Comment by blakadder** [comment]
Is there some sort of workaround to scroll up a bit when using custom anchors?

**Comment by squidfunk** [comment]
You could use the styles that are used for the headlines and target all `[id]` elements.

https://github.com/squidfunk/mkdocs-material/blob/728fef6ec8259e910500885047911c18bae145da/src/assets/stylesheets/extensions/_permalinks.scss#L69-L81

**Comment by blakadder** [comment]
Here's a possible solution:

In the end I assigned `class="cmnd"` to each anchor I wanted this behaviour on and added to extra_css:

```css
.cmnd:target {
    display: block;
    height: 4rem; /*approx same height as header*/
    margin-top: -4rem; /*approx same height as header*/
    visibility: hidden;
}
```
this will avoid unwanted effects if using globally

**Comment by squidfunk** [comment]
Jep, the side effects are the reason why this is not globally applied. Thanks for sharing your solution.
